// Offline demo mode — lets the Vercel site run with the EC2 backend switched off.
//
// Public data (schedule, standings, telemetry) comes from JSON snapshots in
// `demo-data/`, generated by `backend/scripts/snapshot_demo.py` from the same
// endpoint functions the live API uses. User data (login, picks, circles) is
// synthesised statelessly: any username signs in, and a season of picks is
// scored against the real race results so every page has something to show.
import { promises as fs } from "fs"
import path from "path"

// Demo is the default so the site keeps working with no backend. Set
// DEMO_MODE=false (plus API_URL) on Vercel and redeploy to go live again.
export const DEMO_MODE = process.env.DEMO_MODE !== "false"

const DATA_DIR = path.join(process.cwd(), "demo-data")
const SAFE_SEGMENT = /^[A-Za-z0-9_-]+$/

export async function readDemo<T = unknown>(rel: string): Promise<T | null> {
  if (!rel.split("/").every((s) => SAFE_SEGMENT.test(s))) return null
  try {
    return JSON.parse(await fs.readFile(path.join(DATA_DIR, `${rel}.json`), "utf-8")) as T
  } catch {
    return null
  }
}

// ── Response shapes (subset of the backend's) ───────────────────────────────

export interface DemoEvent {
  id: number
  round_number: number
  event_name: string
  is_completed: boolean
  session5_date: string | null
  event_date: string
}

interface RaceResult {
  abbreviation: string
  finish_position: number | null
  is_dnf: boolean
  best_lap_time: number | null
}

interface CompareDriver {
  team_slug: string
  lap_time: number | null
  compound: string | null
  distance: number[]
  time: number[]
  speed: number[]
  throttle: number[]
  brake: number[]
  gear: (number | null)[]
  drs: number[]
  session: string
}

// ── Demo users ──────────────────────────────────────────────────────────────

const TOKEN_PREFIX = "demo."

export function demoToken(username: string): string {
  return TOKEN_PREFIX + Buffer.from(username, "utf-8").toString("base64url")
}

export function demoUser(authHeader: string | null): string | null {
  const token = authHeader?.replace(/^Bearer\s+/i, "") ?? ""
  if (!token.startsWith(TOKEN_PREFIX)) return null
  try {
    return Buffer.from(token.slice(TOKEN_PREFIX.length), "base64url").toString("utf-8") || null
  } catch {
    return null
  }
}

// Deterministic per-round/per-user variation so picks look human, not perfect.
function seed(...parts: (string | number)[]): number {
  let h = 2166136261
  for (const ch of parts.join("|")) {
    h ^= ch.charCodeAt(0)
    h = Math.imul(h, 16777619)
  }
  return h >>> 0
}

// Mirrors the scoring in backend/main.py `score_race` — same point values, same breakdown JSON.
export async function demoPredictions(username: string) {
  const events = (await readDemo<DemoEvent[]>("schedule")) ?? []
  const out = []
  for (const ev of events.filter((e) => e.is_completed)) {
    const rn = ev.round_number
    const summary = await readDemo<{ results?: RaceResult[] }>(`telemetry/${rn}/race_summary`)
    const quali = await readDemo<{ results?: { Abbreviation: string }[] }>(`telemetry/${rn}/quali`)
    const rc = await readDemo<{ summary?: { safety_car?: number } }>(`telemetry/${rn}/race_control`)
    const results = summary?.results ?? []
    if (results.length < 6) continue

    const order = results.map((r) => r.abbreviation)
    const actualPole = quali?.results?.[0]?.Abbreviation ?? order[0]
    const withLap = results.filter((r) => r.best_lap_time != null)
    const actualFl = withLap.reduce((a, b) => (b.best_lap_time! < a.best_lap_time! ? b : a), withLap[0])?.abbreviation
    const actualDnfs = results.filter((r) => r.is_dnf).map((r) => r.abbreviation)
    const actualSc = (rc?.summary?.safety_car ?? 0) > 0

    const s = seed(username, rn)
    const cand = order.slice(0, 6)
    const swap = (i: number, j: number) => ([cand[i], cand[j]] = [cand[j], cand[i]])
    if (s & 1) swap(0, 1)
    if (s & 2) swap(1, 2)
    if (s & 4) swap(3, 5)
    if (s & 128) swap(0, 3)
    if (s & 256) swap(2, 4)
    if (s & 512) swap(4, 5)
    const pick = {
      pole: s & 8 ? order[1] : actualPole,
      fl: s & 16 || s & 1024 ? order[s & 2048 ? 2 : 4] : actualFl,
      dnf: s & 32 && actualDnfs.length ? actualDnfs[0] : order[order.length - 1],
      sc: s & 64 ? !actualSc : actualSc,
    }

    const slot = (p: string | null | undefined, a: string | null | undefined, pts: number) => ({
      pick: p,
      actual: a,
      pts: p && p === a ? pts : 0,
    })
    const breakdown = {
      pole: slot(pick.pole, actualPole, 5),
      p1: slot(cand[0], order[0], 10),
      p2: slot(cand[1], order[1], 10),
      p3: slot(cand[2], order[2], 10),
      p4: slot(cand[3], order[3], 8),
      p5: slot(cand[4], order[4], 6),
      fl: slot(pick.fl, actualFl, 5),
      dnf: { pick: pick.dnf, actual: actualDnfs.join(", "), pts: actualDnfs.includes(pick.dnf) ? 5 : 0 },
      sc: { pick: pick.sc ? "Yes" : "No", actual: actualSc ? "Yes" : "No", pts: pick.sc === actualSc ? 5 : 0 },
    }
    out.push({
      id: rn,
      user_id: 1,
      event_id: ev.id,
      pole_position: pick.pole,
      first_place: cand[0],
      second_place: cand[1],
      third_place: cand[2],
      fourth_place: cand[3],
      fifth_place: cand[4],
      fastest_lap: pick.fl,
      dnf_driver: pick.dnf,
      safety_car: pick.sc,
      points_earned: Object.values(breakdown).reduce((t, b) => t + b.pts, 0),
      score_breakdown: JSON.stringify(breakdown),
    })
  }
  return out
}

const RIVALS = ["boxboxbox", "undercut_uday", "sainz_szn", "tifosi_tanvi", "dirty_air"]

export async function demoLeaderboard(username: string) {
  const own = (await demoPredictions(username)).reduce((t, p) => t + p.points_earned, 0)
  const rows = [
    { username, total_points: own },
    ...(await Promise.all(
      RIVALS.map(async (r) => ({
        username: r,
        total_points: (await demoPredictions(r)).reduce((t, p) => t + p.points_earned, 0),
      })),
    )),
  ].sort((a, b) => b.total_points - a.total_points)
  return rows.map((r, i) => ({ rank: i + 1, ...r }))
}

export const DEMO_GROUPS = [
  { id: 1, name: "Paddock Club", invite_code: "demo2026", member_count: RIVALS.length + 1 },
]

// ── Driver comparison ───────────────────────────────────────────────────────

// Linear interpolation of ys at x over a monotonically increasing xs.
function interp(x: number, xs: number[], ys: number[]): number | null {
  if (!xs.length || x < xs[0] || x > xs[xs.length - 1]) return null
  let lo = 0
  let hi = xs.length - 1
  while (hi - lo > 1) {
    const mid = (lo + hi) >> 1
    if (xs[mid] <= x) lo = mid
    else hi = mid
  }
  const span = xs[hi] - xs[lo]
  return span ? ys[lo] + ((ys[hi] - ys[lo]) * (x - xs[lo])) / span : ys[lo]
}

// Same payload as GET /api/telemetry/{y}/{r}/compare/{d1}/{d2}; the delta is the
// gap in elapsed lap time at each point of d1's lap (positive = d2 slower),
// which is what fastf1.utils.delta_time computes server-side.
export async function demoCompare(rn: string, d1: string, d2: string) {
  const [a, b] = await Promise.all([
    readDemo<CompareDriver>(`compare/${rn}/${d1}`),
    readDemo<CompareDriver>(`compare/${rn}/${d2}`),
  ])
  if (!a || !b) return null
  const strip = ({ time: _t, session: _s, ...rest }: CompareDriver) => rest
  return {
    session: a.session,
    round: Number(rn),
    d1,
    d2,
    drivers: { [d1]: strip(a), [d2]: strip(b) },
    delta: {
      distance: a.distance,
      delta: a.distance.map((d, i) => {
        const t2 = interp(d, b.distance, b.time)
        return t2 == null ? null : Math.round((t2 - a.time[i]) * 1000) / 1000
      }),
    },
  }
}
